// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ElapsedTestSuiteRunTimeController from "./elapsed_test_suite_run_time_controller"
application.register("elapsed-test-suite-run-time", ElapsedTestSuiteRunTimeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LeftPaneController from "./left_pane_controller"
application.register("left-pane", LeftPaneController)

import TerminalScrollController from "./terminal_scroll_controller"
application.register("terminal-scroll", TerminalScrollController)

import TestCaseRunListController from "./test_case_run_list_controller"
application.register("test-case-run-list", TestCaseRunListController)

import TestSuiteRunListController from "./test_suite_run_list_controller"
application.register("test-suite-run-list", TestSuiteRunListController)
