#!/usr/bin/env ruby

require_relative "lib/saturncicli/client"

begin
  client = SaturnCICLI::Client.new(
    username: ENV["USER_ID"],
    password: ENV["USER_API_TOKEN"]
  )

  client.execute(ARGV.join(" "))
rescue StandardError => e
  puts e.message
end
