apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        - name: REGISTRY_HTTP_CLIENT_TIMEOUT
          value: "600s"  # 10 minutes
        - name: REGISTRY_HTTP_REQUESTTIMEOUT
          value: "600s"  # 10 minutes
        - name: REGISTRY_HTTP_RESPONSEHEADER_TIMEOUT
          value: "600s"  # 10 minutes
        - name: REGISTRY_PROXY_REMOTEURL
          value: "https://registry-1.docker.io"
        volumeMounts:
        - name: registry-data
          mountPath: /var/lib/registry
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
      volumes:
      - name: registry-data
        persistentVolumeClaim:
          claimName: registry-pvc
