apiVersion: v1
kind: Service
metadata:
  name: registry-service
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "5000"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "073fe537-ccec-4bf5-8c0c-3cd03b939ed1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
