default:
  store_options: &default_store_options
    max_age: <%= 60.days.to_i %>
    namespace: <%= Rails.env %>
  size_estimate_samples: 1000

production: &production
  databases: production_cache
  store_options:
    <<: *default_store_options
    max_entries: <%= 256.gigabytes %>
