default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

development:
  <<: *default
  database: saturn_development

test:
  <<: *default
  database: saturn_test

production: &production
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME") { nil } %>
    username: <%= ENV.fetch("DATABASE_USERNAME") %>
    password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  cache:
    <<: *production
    database: saturnci-production-db-cache
    migrations_paths: db/cache_migrate
  cable:
    <<: *production
