default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>

development:
  <<: *default
  database: saturn_development

test:
  <<: *default
  database: saturn_test

production: &production
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME", nil) %>
    username: <%= ENV.fetch("DATABASE_USERNAME", nil) %>
    password: <%= ENV.fetch("DATABASE_PASSWORD", nil) %>
  cache:
    <<: *default
    adapter: postgresql
    migrations_paths: db/cache_migrate
    database: <%= ENV.fetch("CACHE_DATABASE_NAME", nil) %>
    host: <%= ENV.fetch("CACHE_DATABASE_HOST", nil) %>
    port: <%= ENV.fetch("CACHE_DATABASE_PORT", nil) %>
    username: <%= ENV.fetch("CACHE_DATABASE_USERNAME", nil) %>
    password: <%= ENV.fetch("CACHE_DATABASE_PASSWORD", nil) %>
  queue:
    <<: *default
    adapter: postgresql
    migrations_paths: db/queue_migrate
    database: <%= ENV.fetch("QUEUE_DATABASE_NAME", nil) %>
    host: <%= ENV.fetch("QUEUE_DATABASE_HOST", nil) %>
    port: <%= ENV.fetch("QUEUE_DATABASE_PORT", nil) %>
    username: <%= ENV.fetch("QUEUE_DATABASE_USERNAME", nil) %>
    password: <%= ENV.fetch("QUEUE_DATABASE_PASSWORD", nil) %>
  cable:
    <<: *production
