default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1
  supervise_test_runners:
    command: "TestRunner.supervise"
    schedule: every ten seconds

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
