version: "3.8"

services:
  saturn_test_app:
    networks:
      saturnci_network:
        ipv4_address: 192.168.1.100
    hostname: saturn_test_app
    build:
      context: ../
      dockerfile: .saturnci/Dockerfile
    image: ${SATURN_TEST_APP_IMAGE_URL:-saturn_test_app}
    volumes:
      - ../:/code
    depends_on:
      - postgres
      - chrome
      - dns
    environment:
      DOCKER_ENV: "true"
      DATABASE_USERNAME: saturn
      DATABASE_PASSWORD: ""
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      RAILS_ENV: test

  postgres:
    image: postgres:17.2-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
      - ./init.sql:/data/application/init.sql
    ports:
      - "5432:5432"
    environment:
      PSQL_HISTFILE: /usr/src/app/log/.psql_history
      POSTGRES_USER: saturn
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U saturn"]
      interval: 10s
      timeout: 2s
      retries: 10
    logging:
      driver: none

  dns:
    image: coredns/coredns:latest
    container_name: saturnci_dns
    networks:
      saturnci_network:
        ipv4_address: 192.168.1.199
    volumes:
      - ./Corefile:/Corefile
    command: [ "-conf", "/Corefile" ]
    restart: unless-stopped

  chrome:
    networks:
      - saturnci_network
    dns: 192.168.1.199
    image: seleniarm/standalone-chromium
    hostname: chrome
    shm_size: 2g
    ports:
      - "4444:4444"

volumes:
  postgresql:

networks:
  saturnci_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
