#!/bin/bash

# Example usage: ./deploy production
# cd into the ops directory before attempting to run this script

APP_VERSION=$(date +%s)
ENVIRONMENT=$1
TAG="$ENVIRONMENT-$APP_VERSION"
echo "Deploying $TAG"

cd ..
docker build --platform linux/amd64 -t $TAG -f Dockerfile.production .
cd -

doctl registry login
docker tag $TAG registry.digitalocean.com/saturnci/saturnci:$TAG
docker push registry.digitalocean.com/saturnci/saturnci:$TAG

./apply $ENVIRONMENT $TAG
