#!/bin/bash

# Get the first running pod with "saturn" in the name
pod=$(kubectl -n production get pods --field-selector=status.phase=Running -o jsonpath="{.items[*].metadata.name}" | tr ' ' '\n' | grep saturn | head -1)

# Start a shell session in the pod
kubectl -n production exec -it $pod -- bash
