apiVersion: batch/v1
kind: Job
metadata:
  name: worker-${RUN_ID}
  namespace: default
spec:
  ttlSecondsAfterFinished: 3600
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        # Worker agent container
        - name: worker-agent
          image: registry.digitalocean.com/saturnci/worker-agent:latest
          env:
            - name: SATURNCI_API_HOST
              value: "https://app.saturnci.com"
            - name: WORKER_ID
              value: "${WORKER_ID}"
            - name: WORKER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: worker-secrets
                  key: access-token
            - name: TEST_SUITE_RUN_ID
              value: "${TEST_SUITE_RUN_ID}"
            - name: RUN_ID
              value: "${RUN_ID}"
            - name: TASK_ID
              value: "${TASK_ID}"
            - name: RUN_ORDER_INDEX
              value: "${RUN_ORDER_INDEX}"
            - name: PROJECT_NAME
              value: "${PROJECT_NAME}"
            - name: BRANCH_NAME
              value: "${BRANCH_NAME}"
            - name: NUMBER_OF_CONCURRENT_RUNS
              value: "${NUMBER_OF_CONCURRENT_RUNS}"
            - name: COMMIT_HASH
              value: "${COMMIT_HASH}"
            - name: RSPEC_SEED
              value: "${RSPEC_SEED}"
            - name: GITHUB_INSTALLATION_ID
              value: "${GITHUB_INSTALLATION_ID}"
            - name: GITHUB_REPO_FULL_NAME
              value: "${GITHUB_REPO_FULL_NAME}"
            - name: CUSTOM_ENV_VARS
              value: "${CUSTOM_ENV_VARS}"
            # Docker host points to DinD sidecar
            - name: DOCKER_HOST
              value: "tcp://localhost:2375"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: repository
              mountPath: /repository

        # Docker-in-Docker sidecar
        - name: dind
          image: docker:24-dind
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          volumeMounts:
            - name: dind-storage
              mountPath: /var/lib/docker
            - name: repository
              mountPath: /repository

      volumes:
        - name: dind-storage
          emptyDir: {}
        - name: repository
          emptyDir: {}
